name: bank-sync-dev
services:
  # PostgreSQL for development
  db_dev:
    image: postgres:latest
    container_name: bank_sync_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_sync_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - bank_network

  # PostgreSQL for e2e tests
  db_test:
    image: postgres:latest
    container_name: bank_sync_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_sync_db_test
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - bank_network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db_dev
      - db_test
    networks:
      - bank_network

  # SonarQube
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - bank_network
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db_dev:5432/sonarqube

networks:
  bank_network:
    driver: bridge

volumes:
  postgres_dev_data:
  postgres_test_data:
