export enum ValidationErrorType {
  MISSING_CHECKPOINT = 'MISSING_CHECKPOINT',
  MISSING_MOVEMENTS = 'MISSING_MOVEMENTS',
  BALANCE_MISMATCH = 'BALANCE_MISMATCH',
  DUPLICATE_MOVEMENT = 'DUPLICATE_MOVEMENT',
  INCONSISTENT_DATE = 'INCONSISTENT_DATE',
  INITIAL_BALANCE_MISMATCH = 'INITIAL_BALANCE_MISMATCH',
  UNEXPECTED_AMOUNT = 'UNEXPECTED_AMOUNT',
  MISSING_TRANSACTION = 'MISSING_TRANSACTION',
  POTENTIAL_MOVEMENT_DUPLICATE = 'POTENTIAL_MOVEMENT_DUPLICATE',
  MISSING_INTERMEDIATE_CHECKPOINT = 'MISSING_INTERMEDIATE_CHECKPOINT',
  INCONSISTENT_BALANCE = 'INCONSISTENT_BALANCE',
}
