export enum ValidationErrorType {
  MISSING_CHECKPOINT = 'MISSING_CHECKPOINT',
  MISSING_MOVEMENTS = 'MISSING_MOVEMENTS',
  BALANCE_MISMATCH = 'BALANCE_MISMATCH',
  DUPLICATE_MOVEMENT = 'DUPLICATE_MOVEMENT',
  INCONSISTENT_DATE = 'INCONSISTENT_DATE',
  UNEXPECTED_AMOUNT = 'UNEXPECTED_AMOUNT',
  POTENTIAL_MOVEMENT_DUPLICATE = 'POTENTIAL_MOVEMENT_DUPLICATE',
}
